### ISSUE TITLE
empty git repo is broken

### ISSUE THREAD

**Issue by whwright** [wright8191/dotfiles#30]
```
Traceback (most recent call last):                                                                                                                           
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 244, in <module>
    main()
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 237, in main
    sys.stdout.write(current_git_status(lines))
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 202, in current_git_status
    remote = parse_ahead_behind(lines[0])
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 118, in parse_ahead_behind
    behind = int(part.replace('behind ', ''))
ValueError: invalid literal for int() with base 10: 'gone'
Traceback (most recent call last):
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 244, in <module>
    main()
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 237, in main
    sys.stdout.write(current_git_status(lines))
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 202, in current_git_status
    remote = parse_ahead_behind(lines[0])
  File "/home/whw/.dotfiles/zsh/zsh-git-prompt.symlink/gitstatus.py", line 118, in parse_ahead_behind
    behind = int(part.replace('behind ', ''))
ValueError: invalid literal for int() with base 10: 'gone'
```

**Comment by whwright** [comment]
I updated to latest commit of https://github.com/starcraftman/zsh-git-prompt where this was fixed, but then this: https://github.com/starcraftman/zsh-git-prompt/issues/31
